name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: download intuit/auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto

      - name: Create Release
        run: ~/auto shipit